//import'./topics/01-basic-types'
//import'./topics/02-objetos-interfaces'
//import'./topics/03-array'
//import './topics/05-funciones-methods'
//import'./topics/04-destructuracion-arrays-objeots'
//import'./topics/06-imports-exports'
//import'./topics/07-classes'
import'./topics/08-generic-types'